### PR TITLE
Revert "Revert "Regex restriction for uniqueValues""

### PR DESCRIPTION
**Pull request by danfruehauf**
Reverts aodn/geoserver-build#101

Reopens https://github.com/aodn/aodn-portal/issues/2080

### CODE REVIEW

**Comment by danfruehauf** [comment]
@jonescc Externalized properly to `filters.xml`.

**Comment by danfruehauf** [comment]
See also:
https://github.com/aodn/geoserver-config/pull/310

**Comment by jonescc** [comment]
@danfruehauf looks good for us.  Will this cause a problem for others using this plugin - should the code default to allowing all if no config file is found for example.

**Comment by jonescc** [comment]
Actually, I can see now you've catered for that.  I'll try it out.

**Pull request merged**
