### PR TITLE
Use java to create csv file from netcdf timeseries file

### PR DESCRIPTION
**Pull request by jonescc**

### CODE REVIEW

**Comment by jonescc** [comment]
Needs https://github.com/aodn/netcdf-iterator/pull/3 to be merged and built with jenkins before this can be merged.

**Comment by jonescc** [comment]
netcdf-iterator merged and built - for review/merge

**Comment by jonescc** [comment]
Updated this slightly to return a human readable message in the event of an error

**Comment by bhasin85** [comment]
Squashed & Merged! :+1:

**Pull request merged**
