### PR TITLE
Issue 2267

### PR DESCRIPTION
**Pull request by bhasin85**
Related [PR](https://github.com/aodn/geoserver-config/pull/386)

### CODE REVIEW

**Comment by anguss00** [comment]
I'm reviewing

**Comment by anguss00** [comment]
I'd be interested if someone else could lend an eye here... I'm running what I think are legitimate requests and getting the same ``Could not obtain list of URLs: 'null'`` exception every time: see below for my example request: 

``<?xml version="1.0" encoding="UTF-8"?><wps:Execute xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" service="WPS" version="1.0.0"><ows:Identifier>gs:GoGoDuck</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>layer</ows:Identifier><wps:Data><wps:LiteralData>srs_sst_l3s_6d_day_gridded_url</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>subset</ows:Identifier><wps:Data><wps:LiteralData>TIME,2000-07-21T15:20:00.000Z,2005-07-21T15:20:00.000Z;LATITUDE,-90.0,90.0;LONGITUDE,-180.0,180.0</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>callbackUrl</ows:Identifier><wps:Data><wps:LiteralData>https://portal-systest.aodn.org.au/wps/jobComplete</wps:LiteralData></wps:Data></wps:Input><wps:Input><ows:Identifier>callbackParams</ows:Identifier><wps:Data><wps:LiteralData>email.to=angus.scheibner@utas.edu.au</wps:LiteralData></wps:Data></wps:Input></wps:DataInputs><wps:ResponseForm><wps:ResponseDocument lineage="false" status="true" storeExecuteResponse="true"><wps:Output asReference="true" mimeType="application/x-netcdf"><ows:Identifier>result</ows:Identifier></wps:Output></wps:ResponseDocument></wps:ResponseForm></wps:Execute>``

**Comment by jonescc** [comment]
Request works fine against geoserver-wps-systest.

**Comment by bhasin85** [comment]
Thanks @jonescc  for looking into it.

**Comment by jonescc** [comment]
It did run out of space - but no null pointer exceptions

**Comment by jonescc** [comment]
Most likely setup issue for @anguss00?   Where were you trying to run this?

**Pull request merged**
