### PR TITLE
Fix mayhem

### PR DESCRIPTION
**Pull request by danfruehauf**
* Import Julian changes (includes WPS implementation)
   * Make CLI work after that (tested!)
 * Fix pom.xml indent
 * Remove redundant repositories from plugins (use repositories from main pom.xml)

Phew.

### CODE REVIEW

**Comment by jonescc** [comment]
I'll review.  Travis not working for this repo?

**Comment by danfruehauf** [comment]
Ah, should work. I'll have a quick look.

**Comment by danfruehauf** [comment]
Just pushed another commit to fix the version of ncdfgenerator (modified to 1.0.0).

**Comment by danfruehauf** [comment]
Travis is good now!

**Comment by jonescc** [comment]
I get a test failing when building locally:

Failed tests:   testGetNcksParameters(au.org.emii.gogoduck.worker.SubsetParametersTest): expected:<PARAM[2,2,3]> but was:<PARAM[3,4,5]>

Have to leave this for now.  Someone else can pick this up tommorrow

**Comment by danfruehauf** [comment]
Possibly changing `SubsetParameters` to inherit from `LinkedHashMap` will solve it, as the order will be kept. I'll need to setup java 8 to test it though.

**Comment by danfruehauf** [comment]
Fixes #32

**Comment by jkburges** [comment]
Can I suggest that instead of changing the code to make tests work (if ordering isn't actually needed), change the test to check that map a "contains all" elements from map b, and not more.

Caveat: replying from my phone, haven't looked at the code, but hopefully it makes sense!

**Comment by danfruehauf** [comment]
So it returns a list of arguments, something along the lines of `-d something1 -d something2`.

It doesn't matter whether it's `-d something1 -d something2` or `-d something2 -d something1`, but I want the `-d` in the right places.

Hope it makes sense.

**Pull request merged**
