### PR TITLE
Add postgres database support for jetty:run

### PR DESCRIPTION
**Pull request by jonescc**
Looked at this while trying to work out how to test my wps changes locally.  

No test data included.  May add some as a part of my testing.

### CODE REVIEW

**Comment by danfruehauf** [comment]
I was thinking `context.xml` should be renamed to `context-sample.xml`. `context.xml` should in fact be in `.gitignore`. That way we'll prevent people from committing passwords etc by accident.

**Comment by jonescc** [comment]
Well, I wasn't planning on putting any production database details in there - just to set up some basic test data.  But yeah I guess to start with people will modify it to connect to something with data.  So yes can add another step to copy context.xml

**Comment by jonescc** [comment]
OK, updated

**Comment by danfruehauf** [comment]
Thanks!

**Pull request merged**
